//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 26.06.2018 15:52:48
namespace WebApplication1.Models
{
    /// <summary>
    /// There are no comments for BaseDocumentSingle in the schema.
    /// </summary>
    public partial class BaseDocumentSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<BaseDocument>
    {
        /// <summary>
        /// Initialize a new BaseDocumentSingle object.
        /// </summary>
        public BaseDocumentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new BaseDocumentSingle object.
        /// </summary>
        public BaseDocumentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new BaseDocumentSingle object.
        /// </summary>
        public BaseDocumentSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<BaseDocument> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for LinkedDocuments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.BaseDocument> LinkedDocuments
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LinkedDocuments == null))
                {
                    this._LinkedDocuments = Context.CreateQuery<global::WebApplication1.Models.BaseDocument>(GetPath("LinkedDocuments"));
                }
                return this._LinkedDocuments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.BaseDocument> _LinkedDocuments;
        /// <summary>
        /// There are no comments for ParentDocument in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.BaseDocumentSingle ParentDocument
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ParentDocument == null))
                {
                    this._ParentDocument = new global::WebApplication1.Models.BaseDocumentSingle(this.Context, GetPath("ParentDocument"));
                }
                return this._ParentDocument;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.BaseDocumentSingle _ParentDocument;
    }
    /// <summary>
    /// There are no comments for BaseDocument in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ID")]
    public abstract partial class BaseDocument : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property LinkedDocuments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.BaseDocument> LinkedDocuments
        {
            get
            {
                return this._LinkedDocuments;
            }
            set
            {
                this.OnLinkedDocumentsChanging(value);
                this._LinkedDocuments = value;
                this.OnLinkedDocumentsChanged();
                this.OnPropertyChanged("LinkedDocuments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.BaseDocument> _LinkedDocuments = new global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.BaseDocument>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnLinkedDocumentsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.BaseDocument> value);
        partial void OnLinkedDocumentsChanged();
        /// <summary>
        /// There are no comments for Property ParentDocument in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.BaseDocument ParentDocument
        {
            get
            {
                return this._ParentDocument;
            }
            set
            {
                this.OnParentDocumentChanging(value);
                this._ParentDocument = value;
                this.OnParentDocumentChanged();
                this.OnPropertyChanged("ParentDocument");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.BaseDocument _ParentDocument;
        partial void OnParentDocumentChanging(global::WebApplication1.Models.BaseDocument value);
        partial void OnParentDocumentChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CustomerSingle in the schema.
    /// </summary>
    public partial class CustomerSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Customer>
    {
        /// <summary>
        /// Initialize a new CustomerSingle object.
        /// </summary>
        public CustomerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CustomerSingle object.
        /// </summary>
        public CustomerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CustomerSingle object.
        /// </summary>
        public CustomerSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Customer> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Order> Orders
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Orders == null))
                {
                    this._Orders = Context.CreateQuery<global::WebApplication1.Models.Order>(GetPath("Orders"));
                }
                return this._Orders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Order> _Orders;
        /// <summary>
        /// There are no comments for Contracts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Contract> Contracts
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Contracts == null))
                {
                    this._Contracts = Context.CreateQuery<global::WebApplication1.Models.Contract>(GetPath("Contracts"));
                }
                return this._Contracts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Contract> _Contracts;
    }
    /// <summary>
    /// There are no comments for Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("CustomerID")]
    public partial class Customer : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of CustomerID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Customer CreateCustomer(string customerID)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this._CustomerID = value;
                this.OnCustomerIDChanged();
                this.OnPropertyChanged("CustomerID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _CustomerID;
        partial void OnCustomerIDChanging(string value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property CompanyName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnCompanyNameChanging(value);
                this._CompanyName = value;
                this.OnCompanyNameChanged();
                this.OnPropertyChanged("CompanyName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _CompanyName;
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        /// <summary>
        /// There are no comments for Property Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.Order> Orders
        {
            get
            {
                return this._Orders;
            }
            set
            {
                this.OnOrdersChanging(value);
                this._Orders = value;
                this.OnOrdersChanged();
                this.OnPropertyChanged("Orders");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.Order> _Orders = new global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.Order>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnOrdersChanging(global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.Order> value);
        partial void OnOrdersChanged();
        /// <summary>
        /// There are no comments for Property Contracts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.Contract> Contracts
        {
            get
            {
                return this._Contracts;
            }
            set
            {
                this.OnContractsChanging(value);
                this._Contracts = value;
                this.OnContractsChanged();
                this.OnPropertyChanged("Contracts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.Contract> _Contracts = new global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.Contract>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnContractsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.Contract> value);
        partial void OnContractsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OrderSingle in the schema.
    /// </summary>
    public partial class OrderSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Order>
    {
        /// <summary>
        /// Initialize a new OrderSingle object.
        /// </summary>
        public OrderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new OrderSingle object.
        /// </summary>
        public OrderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new OrderSingle object.
        /// </summary>
        public OrderSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Order> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.CustomerSingle Customer
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Customer == null))
                {
                    this._Customer = new global::WebApplication1.Models.CustomerSingle(this.Context, GetPath("Customer"));
                }
                return this._Customer;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.CustomerSingle _Customer;
        /// <summary>
        /// There are no comments for OrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.OrderDetail> OrderDetails
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._OrderDetails == null))
                {
                    this._OrderDetails = Context.CreateQuery<global::WebApplication1.Models.OrderDetail>(GetPath("OrderDetails"));
                }
                return this._OrderDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.OrderDetail> _OrderDetails;
        /// <summary>
        /// There are no comments for LinkedDocuments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.BaseDocument> LinkedDocuments
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LinkedDocuments == null))
                {
                    this._LinkedDocuments = Context.CreateQuery<global::WebApplication1.Models.BaseDocument>(GetPath("LinkedDocuments"));
                }
                return this._LinkedDocuments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.BaseDocument> _LinkedDocuments;
        /// <summary>
        /// There are no comments for ParentDocument in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.BaseDocumentSingle ParentDocument
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ParentDocument == null))
                {
                    this._ParentDocument = new global::WebApplication1.Models.BaseDocumentSingle(this.Context, GetPath("ParentDocument"));
                }
                return this._ParentDocument;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.BaseDocumentSingle _ParentDocument;
    }
    /// <summary>
    /// There are no comments for Order in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ID")]
    public partial class Order : BaseDocument
    {
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="orderStatus">Initial value of OrderStatus.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Order CreateOrder(int ID, global::WebApplication1.Models.OrderStatus orderStatus)
        {
            Order order = new Order();
            order.ID = ID;
            order.OrderStatus = orderStatus;
            return order;
        }
        /// <summary>
        /// There are no comments for Property OrderStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.OrderStatus OrderStatus
        {
            get
            {
                return this._OrderStatus;
            }
            set
            {
                this.OnOrderStatusChanging(value);
                this._OrderStatus = value;
                this.OnOrderStatusChanged();
                this.OnPropertyChanged("OrderStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.OrderStatus _OrderStatus;
        partial void OnOrderStatusChanging(global::WebApplication1.Models.OrderStatus value);
        partial void OnOrderStatusChanged();
        /// <summary>
        /// There are no comments for Property Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.Customer Customer
        {
            get
            {
                return this._Customer;
            }
            set
            {
                this.OnCustomerChanging(value);
                this._Customer = value;
                this.OnCustomerChanged();
                this.OnPropertyChanged("Customer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.Customer _Customer;
        partial void OnCustomerChanging(global::WebApplication1.Models.Customer value);
        partial void OnCustomerChanged();
        /// <summary>
        /// There are no comments for Property OrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.OrderDetail> OrderDetails
        {
            get
            {
                return this._OrderDetails;
            }
            set
            {
                this.OnOrderDetailsChanging(value);
                this._OrderDetails = value;
                this.OnOrderDetailsChanged();
                this.OnPropertyChanged("OrderDetails");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.OrderDetail> _OrderDetails = new global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.OrderDetail>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnOrderDetailsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.OrderDetail> value);
        partial void OnOrderDetailsChanged();
    }
    /// <summary>
    /// There are no comments for ContractSingle in the schema.
    /// </summary>
    public partial class ContractSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Contract>
    {
        /// <summary>
        /// Initialize a new ContractSingle object.
        /// </summary>
        public ContractSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ContractSingle object.
        /// </summary>
        public ContractSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ContractSingle object.
        /// </summary>
        public ContractSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Contract> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.CustomerSingle Customer
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Customer == null))
                {
                    this._Customer = new global::WebApplication1.Models.CustomerSingle(this.Context, GetPath("Customer"));
                }
                return this._Customer;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.CustomerSingle _Customer;
        /// <summary>
        /// There are no comments for LinkedDocuments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.BaseDocument> LinkedDocuments
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LinkedDocuments == null))
                {
                    this._LinkedDocuments = Context.CreateQuery<global::WebApplication1.Models.BaseDocument>(GetPath("LinkedDocuments"));
                }
                return this._LinkedDocuments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.BaseDocument> _LinkedDocuments;
        /// <summary>
        /// There are no comments for ParentDocument in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.BaseDocumentSingle ParentDocument
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ParentDocument == null))
                {
                    this._ParentDocument = new global::WebApplication1.Models.BaseDocumentSingle(this.Context, GetPath("ParentDocument"));
                }
                return this._ParentDocument;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.BaseDocumentSingle _ParentDocument;
    }
    /// <summary>
    /// There are no comments for Contract in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ID")]
    public partial class Contract : BaseDocument
    {
        /// <summary>
        /// Create a new Contract object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Contract CreateContract(int ID)
        {
            Contract contract = new Contract();
            contract.ID = ID;
            return contract;
        }
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.Customer Customer
        {
            get
            {
                return this._Customer;
            }
            set
            {
                this.OnCustomerChanging(value);
                this._Customer = value;
                this.OnCustomerChanged();
                this.OnPropertyChanged("Customer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.Customer _Customer;
        partial void OnCustomerChanging(global::WebApplication1.Models.Customer value);
        partial void OnCustomerChanged();
    }
    /// <summary>
    /// There are no comments for ProductSingle in the schema.
    /// </summary>
    public partial class ProductSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Product>
    {
        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Product> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for OrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.OrderDetail> OrderDetails
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._OrderDetails == null))
                {
                    this._OrderDetails = Context.CreateQuery<global::WebApplication1.Models.OrderDetail>(GetPath("OrderDetails"));
                }
                return this._OrderDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.OrderDetail> _OrderDetails;
    }
    /// <summary>
    /// There are no comments for Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ProductID")]
    public partial class Product : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Product CreateProduct(int productID)
        {
            Product product = new Product();
            product.ProductID = productID;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this._ProductID = value;
                this.OnProductIDChanged();
                this.OnPropertyChanged("ProductID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this._ProductName = value;
                this.OnProductNameChanged();
                this.OnPropertyChanged("ProductName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property UnitPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<decimal> UnitPrice
        {
            get
            {
                return this._UnitPrice;
            }
            set
            {
                this.OnUnitPriceChanging(value);
                this._UnitPrice = value;
                this.OnUnitPriceChanged();
                this.OnPropertyChanged("UnitPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<decimal> _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Nullable<decimal> value);
        partial void OnUnitPriceChanged();
        /// <summary>
        /// There are no comments for Property Picture in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public byte[] Picture
        {
            get
            {
                return this._Picture;
            }
            set
            {
                this.OnPictureChanging(value);
                this._Picture = value;
                this.OnPictureChanged();
                this.OnPropertyChanged("Picture");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private byte[] _Picture;
        partial void OnPictureChanging(byte[] value);
        partial void OnPictureChanged();
        /// <summary>
        /// There are no comments for Property OrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.OrderDetail> OrderDetails
        {
            get
            {
                return this._OrderDetails;
            }
            set
            {
                this.OnOrderDetailsChanging(value);
                this._OrderDetails = value;
                this.OnOrderDetailsChanged();
                this.OnPropertyChanged("OrderDetails");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.OrderDetail> _OrderDetails = new global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.OrderDetail>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnOrderDetailsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::WebApplication1.Models.OrderDetail> value);
        partial void OnOrderDetailsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OrderDetailSingle in the schema.
    /// </summary>
    public partial class OrderDetailSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<OrderDetail>
    {
        /// <summary>
        /// Initialize a new OrderDetailSingle object.
        /// </summary>
        public OrderDetailSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new OrderDetailSingle object.
        /// </summary>
        public OrderDetailSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new OrderDetailSingle object.
        /// </summary>
        public OrderDetailSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<OrderDetail> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.OrderSingle Order
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Order == null))
                {
                    this._Order = new global::WebApplication1.Models.OrderSingle(this.Context, GetPath("Order"));
                }
                return this._Order;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.OrderSingle _Order;
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.ProductSingle Product
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Product == null))
                {
                    this._Product = new global::WebApplication1.Models.ProductSingle(this.Context, GetPath("Product"));
                }
                return this._Product;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.ProductSingle _Product;
    }
    /// <summary>
    /// There are no comments for OrderDetail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OrderDetailID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("OrderDetailID")]
    public partial class OrderDetail : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new OrderDetail object.
        /// </summary>
        /// <param name="orderDetailID">Initial value of OrderDetailID.</param>
        /// <param name="unitPrice">Initial value of UnitPrice.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static OrderDetail CreateOrderDetail(int orderDetailID, decimal unitPrice, short quantity)
        {
            OrderDetail orderDetail = new OrderDetail();
            orderDetail.OrderDetailID = orderDetailID;
            orderDetail.UnitPrice = unitPrice;
            orderDetail.Quantity = quantity;
            return orderDetail;
        }
        /// <summary>
        /// There are no comments for Property OrderDetailID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int OrderDetailID
        {
            get
            {
                return this._OrderDetailID;
            }
            set
            {
                this.OnOrderDetailIDChanging(value);
                this._OrderDetailID = value;
                this.OnOrderDetailIDChanged();
                this.OnPropertyChanged("OrderDetailID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _OrderDetailID;
        partial void OnOrderDetailIDChanging(int value);
        partial void OnOrderDetailIDChanged();
        /// <summary>
        /// There are no comments for Property UnitPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public decimal UnitPrice
        {
            get
            {
                return this._UnitPrice;
            }
            set
            {
                this.OnUnitPriceChanging(value);
                this._UnitPrice = value;
                this.OnUnitPriceChanged();
                this.OnPropertyChanged("UnitPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _UnitPrice;
        partial void OnUnitPriceChanging(decimal value);
        partial void OnUnitPriceChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public short Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private short _Quantity;
        partial void OnQuantityChanging(short value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.Order Order
        {
            get
            {
                return this._Order;
            }
            set
            {
                this.OnOrderChanging(value);
                this._Order = value;
                this.OnOrderChanged();
                this.OnPropertyChanged("Order");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.Order _Order;
        partial void OnOrderChanging(global::WebApplication1.Models.Order value);
        partial void OnOrderChanged();
        /// <summary>
        /// There are no comments for Property Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::WebApplication1.Models.Product Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this.OnProductChanging(value);
                this._Product = value;
                this.OnProductChanged();
                this.OnPropertyChanged("Product");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::WebApplication1.Models.Product _Product;
        partial void OnProductChanging(global::WebApplication1.Models.Product value);
        partial void OnProductChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OrderStatus in the schema.
    /// </summary>
    public enum OrderStatus
    {
        New = 0,
        InProgress = 1,
        Completed = 2,
        Cancelled = 3
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.BaseDocument as global::WebApplication1.Models.BaseDocumentSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebApplication1.Models.BaseDocumentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.BaseDocument> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebApplication1.Models.BaseDocumentSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.BaseDocument as global::WebApplication1.Models.BaseDocumentSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="iD">The value of iD</param>
        public static global::WebApplication1.Models.BaseDocumentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.BaseDocument> source,
            int iD)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ID", iD }
            };
            return new global::WebApplication1.Models.BaseDocumentSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.Customer as global::WebApplication1.Models.CustomerSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebApplication1.Models.CustomerSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Customer> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebApplication1.Models.CustomerSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.Customer as global::WebApplication1.Models.CustomerSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="customerID">The value of customerID</param>
        public static global::WebApplication1.Models.CustomerSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Customer> source,
            string customerID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "CustomerID", customerID }
            };
            return new global::WebApplication1.Models.CustomerSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.Order as global::WebApplication1.Models.OrderSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebApplication1.Models.OrderSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Order> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebApplication1.Models.OrderSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.Order as global::WebApplication1.Models.OrderSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="iD">The value of iD</param>
        public static global::WebApplication1.Models.OrderSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Order> source,
            int iD)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ID", iD }
            };
            return new global::WebApplication1.Models.OrderSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Cast an entity of type global::WebApplication1.Models.BaseDocument to its derived type global::WebApplication1.Models.Order
        /// </summary>
        /// <param name="source">source entity</param>
        public static global::WebApplication1.Models.OrderSingle CastToOrder(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::WebApplication1.Models.BaseDocument> source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::WebApplication1.Models.Order> query = source.CastTo<global::WebApplication1.Models.Order>();
            return new global::WebApplication1.Models.OrderSingle(source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.Contract as global::WebApplication1.Models.ContractSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebApplication1.Models.ContractSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Contract> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebApplication1.Models.ContractSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.Contract as global::WebApplication1.Models.ContractSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="iD">The value of iD</param>
        public static global::WebApplication1.Models.ContractSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Contract> source,
            int iD)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ID", iD }
            };
            return new global::WebApplication1.Models.ContractSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Cast an entity of type global::WebApplication1.Models.BaseDocument to its derived type global::WebApplication1.Models.Contract
        /// </summary>
        /// <param name="source">source entity</param>
        public static global::WebApplication1.Models.ContractSingle CastToContract(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::WebApplication1.Models.BaseDocument> source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::WebApplication1.Models.Contract> query = source.CastTo<global::WebApplication1.Models.Contract>();
            return new global::WebApplication1.Models.ContractSingle(source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.Product as global::WebApplication1.Models.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebApplication1.Models.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Product> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebApplication1.Models.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.Product as global::WebApplication1.Models.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="productID">The value of productID</param>
        public static global::WebApplication1.Models.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Product> source,
            int productID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ProductID", productID }
            };
            return new global::WebApplication1.Models.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.OrderDetail as global::WebApplication1.Models.OrderDetailSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebApplication1.Models.OrderDetailSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.OrderDetail> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebApplication1.Models.OrderDetailSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebApplication1.Models.OrderDetail as global::WebApplication1.Models.OrderDetailSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="orderDetailID">The value of orderDetailID</param>
        public static global::WebApplication1.Models.OrderDetailSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.OrderDetail> source,
            int orderDetailID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "OrderDetailID", orderDetailID }
            };
            return new global::WebApplication1.Models.OrderDetailSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Documents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.BaseDocument> Documents
        {
            get
            {
                if ((this._Documents == null))
                {
                    this._Documents = base.CreateQuery<global::WebApplication1.Models.BaseDocument>("Documents");
                }
                return this._Documents;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.BaseDocument> _Documents;
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Customer> Customers
        {
            get
            {
                if ((this._Customers == null))
                {
                    this._Customers = base.CreateQuery<global::WebApplication1.Models.Customer>("Customers");
                }
                return this._Customers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Customer> _Customers;
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Order> Orders
        {
            get
            {
                if ((this._Orders == null))
                {
                    this._Orders = base.CreateQuery<global::WebApplication1.Models.Order>("Orders");
                }
                return this._Orders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Order> _Orders;
        /// <summary>
        /// There are no comments for Contracts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Contract> Contracts
        {
            get
            {
                if ((this._Contracts == null))
                {
                    this._Contracts = base.CreateQuery<global::WebApplication1.Models.Contract>("Contracts");
                }
                return this._Contracts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Contract> _Contracts;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Product> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<global::WebApplication1.Models.Product>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.Product> _Products;
        /// <summary>
        /// There are no comments for OrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.OrderDetail> OrderDetails
        {
            get
            {
                if ((this._OrderDetails == null))
                {
                    this._OrderDetails = base.CreateQuery<global::WebApplication1.Models.OrderDetail>("OrderDetails");
                }
                return this._OrderDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebApplication1.Models.OrderDetail> _OrderDetails;
        /// <summary>
        /// There are no comments for Documents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToDocuments(global::WebApplication1.Models.BaseDocument baseDocument)
        {
            base.AddObject("Documents", baseDocument);
        }
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCustomers(global::WebApplication1.Models.Customer customer)
        {
            base.AddObject("Customers", customer);
        }
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToOrders(global::WebApplication1.Models.Order order)
        {
            base.AddObject("Orders", order);
        }
        /// <summary>
        /// There are no comments for Contracts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToContracts(global::WebApplication1.Models.Contract contract)
        {
            base.AddObject("Contracts", contract);
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToProducts(global::WebApplication1.Models.Product product)
        {
            base.AddObject("Products", product);
        }
        /// <summary>
        /// There are no comments for OrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToOrderDetails(global::WebApplication1.Models.OrderDetail orderDetail)
        {
            base.AddObject("OrderDetails", orderDetail);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""WebApplication1.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""BaseDocument"" Abstract=""true"">
        <Key>
          <PropertyRef Name=""ID"" />
        </Key>
        <Property Name=""ID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Date"" Type=""Edm.DateTimeOffset"" />
        <NavigationProperty Name=""LinkedDocuments"" Type=""Collection(WebApplication1.Models.BaseDocument)"" />
        <NavigationProperty Name=""ParentDocument"" Type=""WebApplication1.Models.BaseDocument"" />
      </EntityType>
      <EntityType Name=""Customer"">
        <Key>
          <PropertyRef Name=""CustomerID"" />
        </Key>
        <Property Name=""CustomerID"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""CompanyName"" Type=""Edm.String"" />
        <NavigationProperty Name=""Orders"" Type=""Collection(WebApplication1.Models.Order)"" />
        <NavigationProperty Name=""Contracts"" Type=""Collection(WebApplication1.Models.Contract)"" />
      </EntityType>
      <EntityType Name=""Order"" BaseType=""WebApplication1.Models.BaseDocument"">
        <Property Name=""OrderStatus"" Type=""WebApplication1.Models.OrderStatus"" Nullable=""false"" />
        <NavigationProperty Name=""Customer"" Type=""WebApplication1.Models.Customer"" />
        <NavigationProperty Name=""OrderDetails"" Type=""Collection(WebApplication1.Models.OrderDetail)"" />
      </EntityType>
      <EntityType Name=""Contract"" BaseType=""WebApplication1.Models.BaseDocument"">
        <Property Name=""Number"" Type=""Edm.String"" />
        <NavigationProperty Name=""Customer"" Type=""WebApplication1.Models.Customer"" />
      </EntityType>
      <EntityType Name=""Product"">
        <Key>
          <PropertyRef Name=""ProductID"" />
        </Key>
        <Property Name=""ProductID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ProductName"" Type=""Edm.String"" />
        <Property Name=""UnitPrice"" Type=""Edm.Decimal"" />
        <Property Name=""Picture"" Type=""Edm.Binary"" />
        <NavigationProperty Name=""OrderDetails"" Type=""Collection(WebApplication1.Models.OrderDetail)"" />
      </EntityType>
      <EntityType Name=""OrderDetail"">
        <Key>
          <PropertyRef Name=""OrderDetailID"" />
        </Key>
        <Property Name=""OrderDetailID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""UnitPrice"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""Quantity"" Type=""Edm.Int16"" Nullable=""false"" />
        <NavigationProperty Name=""Order"" Type=""WebApplication1.Models.Order"" />
        <NavigationProperty Name=""Product"" Type=""WebApplication1.Models.Product"" />
      </EntityType>
      <EnumType Name=""OrderStatus"">
        <Member Name=""New"" Value=""0"" />
        <Member Name=""InProgress"" Value=""1"" />
        <Member Name=""Completed"" Value=""2"" />
        <Member Name=""Cancelled"" Value=""3"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Action Name=""InitializeDatabase"" />
      <Function Name=""TotalSalesByYear"">
        <Parameter Name=""year"" Type=""Edm.Int32"" Nullable=""false"" />
        <ReturnType Type=""Edm.Decimal"" Nullable=""false"" Scale=""Variable"" />
      </Function>
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Documents"" EntityType=""WebApplication1.Models.BaseDocument"">
          <NavigationPropertyBinding Path=""LinkedDocuments"" Target=""Documents"" />
          <NavigationPropertyBinding Path=""ParentDocument"" Target=""Documents"" />
          <NavigationPropertyBinding Path=""WebApplication1.Models.Order/Customer"" Target=""Customers"" />
          <NavigationPropertyBinding Path=""WebApplication1.Models.Order/OrderDetails"" Target=""OrderDetails"" />
          <NavigationPropertyBinding Path=""WebApplication1.Models.Contract/Customer"" Target=""Customers"" />
        </EntitySet>
        <EntitySet Name=""Customers"" EntityType=""WebApplication1.Models.Customer"">
          <NavigationPropertyBinding Path=""Orders"" Target=""Orders"" />
          <NavigationPropertyBinding Path=""Contracts"" Target=""Contracts"" />
        </EntitySet>
        <EntitySet Name=""Orders"" EntityType=""WebApplication1.Models.Order"">
          <NavigationPropertyBinding Path=""LinkedDocuments"" Target=""Documents"" />
          <NavigationPropertyBinding Path=""ParentDocument"" Target=""Documents"" />
          <NavigationPropertyBinding Path=""Customer"" Target=""Customers"" />
          <NavigationPropertyBinding Path=""OrderDetails"" Target=""OrderDetails"" />
        </EntitySet>
        <EntitySet Name=""Contracts"" EntityType=""WebApplication1.Models.Contract"">
          <NavigationPropertyBinding Path=""LinkedDocuments"" Target=""Documents"" />
          <NavigationPropertyBinding Path=""ParentDocument"" Target=""Documents"" />
          <NavigationPropertyBinding Path=""Customer"" Target=""Customers"" />
        </EntitySet>
        <EntitySet Name=""Products"" EntityType=""WebApplication1.Models.Product"">
          <NavigationPropertyBinding Path=""OrderDetails"" Target=""OrderDetails"" />
        </EntitySet>
        <EntitySet Name=""OrderDetails"" EntityType=""WebApplication1.Models.OrderDetail"">
          <NavigationPropertyBinding Path=""Order"" Target=""Orders"" />
          <NavigationPropertyBinding Path=""Product"" Target=""Products"" />
        </EntitySet>
        <ActionImport Name=""InitializeDatabase"" Action=""Default.InitializeDatabase"" />
        <FunctionImport Name=""TotalSalesByYear"" Function=""Default.TotalSalesByYear"" IncludeInServiceDocument=""true"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
        /// <summary>
        /// There are no comments for TotalSalesByYear in the schema.
        /// </summary>
        public global::Microsoft.OData.Client.DataServiceQuerySingle<decimal> TotalSalesByYear(int year)
        {
            return this.CreateFunctionQuerySingle<decimal>("", "TotalSalesByYear", false, new global::Microsoft.OData.Client.UriOperationParameter("year", year));
        }
        /// <summary>
        /// There are no comments for InitializeDatabase in the schema.
        /// </summary>
        public global::Microsoft.OData.Client.DataServiceActionQuery InitializeDatabase()
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuery(this, this.BaseUri.OriginalString.Trim('/') + "/InitializeDatabase");
        }
    }
}
